### ISSUE TITLE
Add cordon/uncordon fencing agent

### ISSUE THREAD

**Issue by jfriesse** [rootfs/node-fencing#41]
Idea is to use infrastructure of existing Clusterlabs fencing agents (https://github.com/ClusterLabs/fence-agents) and add new one which supports cordon/uncordon.

This will need to add kubectl in the fencing agent image.

**Comment by ingvagabund** [comment]
Would be interesting to actually see how much time the cordon operation takes for nodes with a lot of pods.

**Comment by jfriesse** [comment]
With fencing being handled by ansible I don't think we need agent (it was there to fit kordon into configuration) - simple calling kubectl does same job and that is perfectly doable from ansible.
